'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ResFile
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Guild_Wars_2.ResFile", GetType(ResFile).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _05c307d86bb0148742d2a9dd500b87510643ec8d01032b625f7901a14a6cdaee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_05c307d86bb0148742d2a9dd500b87510643ec8d01032b625f7901a14a6cdaee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _1ac6458af0f6a08b237a971fece4b6a9__my_girlfriend_to_my_boyfriend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1ac6458af0f6a08b237a971fece4b6a9__my_girlfriend_to_my_boyfriend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _1fd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1fd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _3dae1aa202456a1371be0fd1affd6016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3dae1aa202456a1371be0fd1affd6016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _4Z8jB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4Z8jB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5599c66a2269e932b44f1ba9fc33f6ed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5599c66a2269e932b44f1ba9fc33f6ed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _5cbe431b8f2a8425ded9bbaa7dc3d2e973f36c8f487dcae5a93573f76fb4e56e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5cbe431b8f2a8425ded9bbaa7dc3d2e973f36c8f487dcae5a93573f76fb4e56e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _74cfd79957008ede0682ba4b8e026dfe173b104aa732b4c62d5e0f5ccbdf08e6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_74cfd79957008ede0682ba4b8e026dfe173b104aa732b4c62d5e0f5ccbdf08e6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property b27dbc0c592761f524e854d93d200f21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b27dbc0c592761f524e854d93d200f21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property c69() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c69", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property cant_find_the_frisbee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cant_find_the_frisbee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Charr_Cat4450Pop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Charr_Cat4450Pop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ColinJohanson_2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColinJohanson_2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property e39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Ff0Il8v() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ff0Il8v", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Gembox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gembox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Guild_wars_2_85a28e_4064852() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guild_wars_2_85a28e_4064852", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property guild_wars_2_has_funny_bugs_o_4688161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guild_wars_2_has_funny_bugs_o_4688161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property guild_wars_2_o_566858() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guild_wars_2_o_566858", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property GW2_how_does_it_feel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GW2_how_does_it_feel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property gw2_jumping_puzzle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gw2_jumping_puzzle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Hype_Train() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hype_Train", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property oh_guild_wars_2_o_866988() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oh_guild_wars_2_o_866988", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TGAMN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TGAMN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property the_night_before_guild_wars_2_o_657766() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("the_night_before_guild_wars_2_o_657766", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property vista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
